name: CI/CD pipeline

on:
    push:
      branches:
        - master
        - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install nodeJs
              uses: actions/setup-node@v4

            - name : install dependencies
              run: npm install
              
         #  - name: run tests
          #   run : |
         #       node server.js
         #        curl http://localhost:3000 



            

        

